# Chat Service Configuration
server:
  port: 8083

spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:mysql://localhost:3306/server_community
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
  expiration: 3600000

group:
  service:
    url: http://localhost:8081